### ISSUE TITLE
bower.io repository

### ISSUE THREAD

**Issue by Andrey-mp** [tamtakoe/oi.file#17]
Hello, 
Could you add a tag (like in oi.select project) to this project?
I've added this project to bower.io repository but it doesn't have any version and coldn't be installed via npm.

Regards,
Andrey.

**Comment by tamtakoe** [comment]
I added 0.0.0 tag

**Comment by Andrey-mp** [comment]
Thank you!
http://bower.io/search/?q=oi.file
Now it can be installed via 'npm install'
