### ISSUE TITLE
Unable to load file. Server problem

### ISSUE THREAD

**Issue by hiworder** [tamtakoe/oi.file#5]
![2014-01-14 09 14 20](https://f.cloud.github.com/assets/5527532/1907380/21c62cf6-7cca-11e3-8539-be52ea22c029.png)
В чем проблема?

**Comment by highfeed** [comment]
Такая же проблема.

**Comment by highfeed** [comment]
Если ответ от сервера не равен 1, то показывается эта ошибка.
